version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: dev
    ports:
      - '3000:3000'
    links:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - 'mysql'
    networks:
      - backend

  mysql:
    container_name: 'mysqlnode'
    platform: linux/amd64
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST_IP=mysqlnode
    networks:
      - backend

networks:
  backend:
    driver: bridge
